language: node_js
node_js:
  - 7
  - 6
  - 4
sudo: false
before_install:
- export PATH=$HOME/.yarn/bin:$PATH
cache: yarn
install:
- yarn install
script:
- yarn ci_tests
after_success:
- export CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
- export CI_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
- export CI_BRANCH="$TRAVIS_BRANCH"
- yarn coveralls